development: &development-active-poi
  pois:
  - osmName: opening_hours
    panel_name: hour
    options:
      open:
        msg: 'Open'
        color: '60ad51'
      soon:
        msg: 'Closing soon'
        time: 60
        color: 'c45713'
      closed:
        msg: 'Closed'
        color: '8c0212'
  - osmName: happy_hours
    panel_name: hour
    options:
      open:
        msg: 'happy hours!'
        color: 'fcc035'
      soon:
        msg: 'Last paint'
        time: 60
        color: '3f76e2'
      closed:
        msg: 'Closed'
        color: '8c0212'
  - osmName: brewery
    panel_name: brewery
  - osmName: phone
    panel_name: phone
  - osmName: website
    panel_name: website
  - osmName: wikidata
    panel_name: wiki

local:
  <<: *development-active-poi

production:
  <<: *development-active-poi
