development: &development-active-poi
  pois:
  - opening_hours
  - happy_hours
  - brewery
  - phone
  - website
  - wikidata

local:
  <<: *development-active-poi

production:
  <<: *development-active-poi
