PORT: 3000

# Services
services:
  geocoder:
    url: override by environment
  idunn:
    url: override by environment
  elk:
    url: override by environment

# System
system:
  baseUrl: /
  timeout: 3
  evalFiles: false
  showError: false

# Store
store:
  name: masq # local_store | none | masq | ..
  endpoint: https://sync-beta.qwantresearch.com/
  masq:
    title: Qwant Maps PoC
    desc: A generic app that uses Masq for storage
    icon: https://camo.githubusercontent.com/8b35d12bd9682a31446b08c1483145653aa5006f/68747470733a2f2f692e696d6775722e636f6d2f715a33647130512e706e67

# Map style
mapStyle:
  baseMapUrl: override by environment
  poiMapUrl: override by environment
  spritesUrl:
    https://qwantresearch.github.io/qwant-basic-gl-style/
  fontUrl:
    https://qwantresearch.github.io/fonts/
