#Pois
pois:
- osmName: opening_hours
  panel_name: hour
  options:
    title: _('Opening hours')
    messages:
      open:
        msg: _('Open')
        color: '#60ad51'
      soon:
        msg: _('Closing soon')
        time: 60
        color: '#c45713'
      closed:
        msg: _('Closed')
        color: '#8c0212'
- osmName: happy_hours
  panel_name: hour
  options:
    title: _('Happy hours')
    messages:
      open:
        msg: _('happy hours!')
        color: '#fcc035'
      soon:
        msg: _('Last pint')
        time: 60
        color: '#3f76e2'
      closed:
        msg: _('Closed')
        color: '#8c0212'
- osmName: brewery
  panel_name: brewery
- osmName: phone
  panel_name: phone
- osmName: website
  panel_name: website
- osmName: wikidata
  panel_name: wiki

# Services
services:
  geocoder:
    url: override by environment


# Language
languages:
  supportedLanguages:
    - &default
      locale: en_GB
      code: en
    -
      locale: fr_FR
      code: fr

  defaultLanguage: *default

# System
system:
  baseUrl: /
  timeout: 3
  evalFiles: false

# Store
store:
  name: masq # local_store | none | masq | ..
  endpoint: https://sync-beta.qwantresearch.com/
  masq:
    title: Qwant Maps PoC
    desc: A generic app that uses Masq for storage
    icon: https://camo.githubusercontent.com/8b35d12bd9682a31446b08c1483145653aa5006f/68747470733a2f2f692e696d6775722e636f6d2f715a33647130512e706e67

# Map style
mapStyle:
  tileserver_base: override by environment
  tileserver_poi: override by environment
  spriteserver:
    https://qwantresearch.github.io/qwant-basic-gl-style/
  fontserver:
    https://qwantresearch.github.io/fonts/
