development: &development-filters
  active : false
  categories:
    - None
    - Boulangerie
    - Musée
    - Restaurant

local:
  <<: *development-filters

production:
  <<: *development-filters

test:
  <<: *development-filters
