development: &development-lang
  supportedLanguages:
    - &default
      locale: en_GB
      code: en
    -
      locale: fr_FR
      code: fr

  defaultLanguage: *default

local:
  <<: *development-lang

production:
  <<: *development-lang

test:
  <<: *development-lang