development: &development-services
  tz:
   url: 'http://localhost:4040/tz/'
   active: true
 wiki:
   url: 'http://localhost:4040/wiki/'
   active: true

production:
  tz:
    active: false
  wiki:
    active: false
