development: &development-services
  tz:
    url: 'http://***REMOVED***:4040/tz/'
    active: true
  wiki:
    url: 'http://***REMOVED***:4040/wiki/'
    active: true

local:
  <<: *development-services

test:
  <<: *development-services

production:
  tz:
    active: false
  wiki:
    active: false
